---
# `authors` requires a list of strings representing the name of a commit author you want to include in the metrics.
authors:
  - "<author>"

# `emails` requires a list of strings representing emails for a commit author you want to include in the metrics.
emails:
  - "<email>"

# `repo_path` requires an array of string representation of the absolute path to the list of repos for which you want metrics.
repo_paths:
  - "<path>"

# `exclude_repos` requires an array of string representation of the absolute path to the list of repos that should be removed from consideration.
repo_paths:
  - "<path>"

# `languages_url` is the link to the latest GitHub Linguist known language list, and should not be altered.
languages_url: "https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml"
